
add_newline = false

[username]
style_user = "#33FFBD"
format = "[$user]($style)"
show_always = false

[hostname]
style = "#33FFBD"
format = "[@$hostname]($style) "
ssh_only = true

[directory]
style = "#005FAF"
read_only = " ï ½"

[git_branch]
symbol = "ï˜ "

[aws]
symbol = "îŒ½  "

[buf]
symbol = "ï’ "
format = "via [$symbol]($style)"

[c]
symbol = "î˜ "

[conda]
symbol = "ï„Œ "

[dart]
symbol = "î˜ "
format = "via [$symbol]($style)"

[docker_context]
symbol = "ïŒˆ "

[dotnet]
format = "[$symbol(ğŸ¯ $tfm )]($style)"

[elixir]
symbol = "î‰µ "
format = "via [$symbol]($style)"

[elm]
symbol = "î˜¬ "
format = "via [$symbol]($style)"

[golang]
symbol = "î˜§ "
format = "via [$symbol]($style)"

[haskell]
symbol = "î· "

[hg_branch]
symbol = "ï˜ "

[java]
symbol = "î‰– "

[julia]
symbol = "î˜¤ "
format = "via [$symbol]($style)"

[memory_usage]
symbol = "ï¡š "

[nim]
symbol = "ïš¤ "

[nix_shell]
symbol = "ï‹œ "

[nodejs]
symbol = "îœ˜ "
format = "via [$symbol]($style)"

[package]
symbol = "ï£– "

[python]
symbol = "îˆµ "
format = "via [$symbol]($style)"

[spack]
symbol = "ğŸ…¢ "

[rust]
symbol = "î¨ "
format = "via [$symbol]($style)"

[vagrant]
format = "via [$symbol]($style)"

